### COMPANIAS
POST http://localhost:5016/api/v1/besigabi/creacionTurnos/companias
Content-Type: application/json

{
	"idSede": -1
}

### SEDES
GET http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/sedes

### TIPO SERVICIO
POST http://localhost:5016/api/v1/besigabi/creacionTurnos/tipoServicio
Content-Type: application/json

{
	"idSede": 1,
	"idCompania": -1,
	"codigoModulo": 4000
}

### VERIFICAR CONFIG COMPANIAS
GET  http://localhost:5016/api/v1/besigabi/creacionTurnos/verificarConfigCompanias

### MODULOS
POST http://localhost:5016/api/v1/besigabi/creacionTurnos/modulos
Content-Type: application/json

{
	"idSede": 1
}

### TIPO TURNO
POST http://localhost:5016/api/v1/besigabi/creacionTurnos/tipoTurno
Content-Type: application/json

{
	"idSede": 1,
	"idServicio": 2
}

### CONFIRMAR CONFIG SEDES
GET http://localhost:5016/api/v1/besigabi/creacionTurnos/confirmarConfigSedes

### TIPO DOCUMENTO
GET http://localhost:5016/api/v1/besigabi/creacionTurnos/tipoDocumento


### CREAR TURNO
POST http://localhost:5016/api/v1/besigabi/creacionTurnos
Content-Type: application/json

{
  "accion": "Nuevo",
  "idSede": 1,
  "idCompania": -1,
  "idTipoTurno": 1,
  "idServicio": 3,
  "CodigoModulo": "4000",
  "NombreModulo": "Modulo Prueba",
  "origen": 1,
  "paciente": {
    "idPaciente": 0,
    "numeroDocumento": "bygy+9615m4=",
    "apellido1": "Perez",
    "apellido2": "",
    "nombre1": "Juan",
    "nombre2": "",
    "sexo": 1,
    "idTipoDocumento": 1,
    "nomTipoDocumento": "DNI",
    "fechaNacimiento": "1980-01-01"
  }
}

### CARGAR CONFIG LIS
GET http://localhost:5016/api/v1/besigabi/creacionTurnos/cargarConfigLIS




/////////////////////////////////////////////////////////////////////////
//                         SKL										/////
/////////////////////////////////////////////////////////////////////////

### TAQUILLAS
POST http://192.168.1.241:5016/api/v1/besigabi/skl/taquillas
Content-Type: application/json

{
	"idSede": 1,
  "codModulo": 4000
}

### SERVICIOS SIGA
POST http://192.168.1.241:5016/api/v1/besigabi/skl/serviciosSiga
Content-Type: application/json

{
  "idSede": 1,
  "codModulo": 4000
}


### SEDES USUARIO
POST http://localhost:5016/api/v1/besigabi/skl/sedesUsuario
Content-Type: application/json

{
  "usuario": "CATALINA"
}

### CONSUMIR CREDENCIALES
POST http://localhost:5016/api/v1/besigabi/skl/consumirCredenciales
Content-Type: application/json

{
  "usuario": "CATALINA",
  "contrasena": "deLN3a9Z7Xs="
}

### TURNO DISPONIBLES (CON ORDEN)
POST http://localhost:5016/api/v1/besigabi/skl/turnosDisponibles
Content-Type: application/json

{
  "idServicio": 3,
  "idSede": 1
}

