### COMPANIAS
POST http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/companias
Content-Type: application/json

{
	"idSede": 1
}

### SEDES
GET http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/sedes

### TIPO SERVICIO
POST http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/tipoServicio
Content-Type: application/json

{
	"idSede": 1,
	"idCompania": 1,
	"codigoModulo": "200"
}

### VERIFICAR CONFIG COMPANIAS
GET  http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/verificarConfigCompanias

### MODULOS
POST http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/modulos
Content-Type: application/json

{
	"idSede": 1
}

### TIPO TURNO
POST http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/tipoTurno
Content-Type: application/json

{
	"idSede": 1,
	"idServicio": 2
}

### CONFIRMAR CONFIG SEDES
GET http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/confirmarConfigSedes

### TIPO DOCUMENTO
GET http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/tipoDocumento


### CREAR TURNO
POST http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos
Content-Type: application/json

{
  "accion": "Nuevo",
  "idSede": 1,
  "idCompania": -1,
  "idTipoTurno": 1,
  "idServicio": 3,
  "CodigoModulo": "200",
  "NombreModulo": "Modulo Prueba",
  "origen": 1,
  "paciente": {
    "idPaciente": 0,
    "numeroDocumento": "bygy+9615m4=",
    "apellido1": "Perez",
    "apellido2": "",
    "nombre1": "Juan",
    "nombre2": "",
    "sexo": 1,
    "idTipoDocumento": 1,
    "nomTipoDocumento": "DNI",
    "fechaNacimiento": "1980-01-01"
  }
}

### CARGAR CONFIG LIS
GET http://192.168.1.241:5016/api/v1/besigabi/creacionTurnos/cargarConfigLIS




/////////////////////////////////////////////////////////////////////////
//                         SKL										/////
/////////////////////////////////////////////////////////////////////////

### TAQUILLAS
POST http://localhost:5016/api/v1/besigabi/skl/taquillas
Content-Type: application/json

{
	"idSede": 1,
  "codModulo": 4000
}

### SERVICIOS SIGA
POST http://localhost:5016/api/v1/besigabi/skl/serviciosSiga
Content-Type: application/json

{
  "idSede": 1,
  "codModulo": 4000
}


### SEDES USUARIO
POST http://192.168.1.241:5016/api/v1/besigabi/skl/sedesUsuario
Content-Type: application/json

{
  "usuario": "CATALINA"
}

### CONSUMIR CREDENCIALES
POST http://192.168.1.241:5016/api/v1/besigabi/skl/consumirCredenciales
Content-Type: application/json

{
  "usuario": "CATALINA",
  "contrasena": "deLN3a9Z7Xs="
}

### TURNO DISPONIBLES (CON ORDEN)
POST http://localhost:5016/api/v1/besigabi/skl/turnosDisponibles
Content-Type: application/json

{
  "idServicio": 3,
  "idSede": 1
}



////////////////////servicios siga lis nt////////////////////

### SEDES ESTRUCTURA NT
GET http://192.168.1.241:5016/api/branch/getAll

### SERVICIOS ESTRUCTURA NT
GET http://192.168.1.241:5016/api/service/getByBranch/1

### PUNTOS DE ATENCION NT
GET http://192.168.1.241:5016/api/pointsOfCare  

### TAQUILLAS POR SEDE SERVICIO
GET http://192.168.1.241:5016/api/taquillasxSedeServicio/1/5

### MOTIVOS DE DESCANSO
GET http://192.168.1.241:5016/api/reasons/break

### ESTADO DE LA TAQUILLA
POST http://192.168.1.241:5016/api/log
Content-Type: application/json

{
	"action": 4,
	"branch": {
		"id": 1,
		"state": 1
	},
	"point": {
		"id": 1,
		"managePriority": true
	},
	"user": {
		"id": 1,
		"user": "andres",
		"lastName": "sanchez",
		"name": "andres"
	}
}

### ESTADO DE LA ATENCION
POST http://192.168.1.241:5016/api/logAtencion
Content-Type: application/json

{
	"id": 0,
	"state": 6,
	"user": {
		"id": 0,
		"user": "andres",
		"lastName": "sanchez",
		"name": "andres"
	},
	"turn": {
		"id": 1
	},
	"service": {
		"id": 3
	},
	"pointOfCare": {
		"id": 1
	}
}

### MOTIVOS DE CANCELACION
GET http://192.168.1.241:5016/api/reasons/cancel

### SERVICIOS DISPONIBLES PARA TRANSFERENCIA
GET http://192.168.1.241:5016/api/reasons/transfer/1/1/1  

### LLAMAR TURNOS GET
GET http://192.168.1.241:5016/api/turns/call/1/3

### LLAMAR TURNOS POST
POST http://192.168.1.241:5016/api/turns/call
Content-Type: application/json

{
	"idTurn": 1,
	"point": {
		"branch": {
			"id": 1
		},
		"service": {
			"id": 3
		},
		"point": {
			"id": 1
		},
		"user": {
			"id": 1,
			"user": "andres",
			"lastName": "sanchez",
			"name": "andres"
		}
	},
	"user": {
		"id": 1,
		"user": "andres",
		"lastName": "sanchez",
		"name": "andres"
	}
}


### TURNO DISPONIBLE MANUAL
GET http://192.168.1.241:5016/api/turns/daily/1/3/sanchez/andres/andres/1	

### TRANSFERIR TURNO
POST http://192.168.1.241:5016/api/transfers
Content-Type: application/json

{
	"idTurn": 1,
	"turnsMovement": [
		{
			"turn": {
				"id": 2
			},
			"user": {
				"id": 1
			},
			"service": {
				"id": 3
			},
			"pointOfCare": {
				"id": 1
			},
			"branch": {
				"id": 1
			},
			"state": 1,
			"active": 1,
			"transfer": true
		},
		{
			"turn": {
				"id": 1
			},
			"user": {
				"id": 1,
				"user": "andres",
				"lastName": "sanchez",
				"name": "andres"
			},
			"service": {
				"id": 1
			},
			"pointOfCare": {
				"id": 1
			},
			"branch": {
				"id": 1
			},
			"state": 1,
			"active": 1,
			"transfer": false
		}
	],
	"user": {
		"id": 1,
		"user": "andres",
		"lastName": "sanchez",
		"name": "andres"
	}
}	

